apiVersion: v1
kind: ConfigMap
metadata:
  name: boatswain
data:
  nats-url: "nats://otterly-secure:46aa9a8bbb3c474302bb@nats-client:4222"
  created-subject: 'test_suite.*.created'
  queue-name: 'workers'
  rollbar-token: 'not_set'
